server:
  port: 8082

spring:
  application:
    name: Book-Service

  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

  messages:
    encoding: UTF-8

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:sqlserver://localhost:1433;databaseName=bookdb;encrypt=true;trustServerCertificate=true;sendStringParametersAsUnicode=true;}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:123}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

fastapi:
  predictor:
    url: ${FASTAPI_PREDICTOR_URL:http://127.0.0.1:8000/predict}